name: sim2real
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2022.3.18=h06a4308_0
  - certifi=2021.10.8=py38h06a4308_2
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1n=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py38h06a4308_0
  - sqlite=3.38.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - cloudpickle==2.0.0
    - cogenvdecoder==0.1.29
    - cycler==0.11.0
    - fonttools==4.31.2
    - grpcio==1.44.0
    - gym==0.20.0
    - gym-unity==0.28.0
    - kiwisolver==1.4.1
    - matplotlib==3.5.1
    - mlagents-envs==0.28.0
    - numpy==1.22.3
    - opencv-python==4.5.5.64
    - packaging==21.3
    - pillow==9.0.1
    - protobuf==3.19.4
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - scipy==1.8.0
    - six==1.16.0
